### ISSUE TITLE
Not starting((

### ISSUE THREAD

**Issue by khudia** [matzeso/quasar-app-extension-tailwindcss#5]
Extension(tailwindcss): is not compatible with @quasar/app v2.0.9. Required version: ^1.0.0

**Comment by KINGER404** [comment]
Have same problem

**Comment by khudia** [comment]
Fixed by hands) changed dependencies strait in node modules? in this package config ))

**Comment by matzeso** [comment]
Hey, thanks for bringing this to my attention.
I bumped the version to 1.0.0 as it seems that that is a new requirement by @quasar/app.
As of now in https://www.npmjs.com/package/quasar-app-extension-tailwindcss it still shows 0.1.5 but I hope it will update soon.
So just require version ^1.0.0 for the extension and update npm and it should work.
Let me know if not, then I will reopen this issue.
